version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4040:3000
    networks:
      static_network:
        ipv4_address: 172.16.0.2
    depends_on:
      - db
    environment:
      - DATABASE_HOST=172.16.0.3
  db:
    image: postgres:13-alpine
    networks:
      static_network:
        ipv4_address: 172.16.0.3
    environment:
      - POSTGRES_USER=your_username
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=your_database_name

networks:
  static_network:
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24