default: &default
  adapter: postgresql
  encoding: unicode
  database: your_database_name
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: your_username
  password: your_password
  host: db

development:
  <<: *default
  database: your_database_name
  

test:
 <<: *default
  database: your_database_name

production:
  <<: *default
  database: your_database_name
